services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    # volumes:
    #   - ./loki-config/:/etc/loki/

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config/config.yaml:/etc/promtail/config.yaml
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      # Mounts the local prometheus.yml config file into the container
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # Persists the collected metrics data across container restarts
      - prometheus_data:/prometheus
    command:
      # Specifies the configuration file location explicitly
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      # Maps host port 9090 to container port 9090
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    environment:
      - gf_paths_provisioning=/etc/grafana/provisioning
      - gf_auth_anonymous_enabled=true
      - gf_auth_anonymous_org_role=admin
    depends_on:
      - loki
      - prometheus

volumes:
  prometheus_data: {} # Defines
