apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-api
    app_gateway_auth_policy: enabled
  name: gateway-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  strategy:
    type: RollingUpdate # This is the default, but explicitly defining it is good practice
    rollingUpdate:
      maxUnavailable: 1 # Can be an absolute number (1) or percentage ('25%')
  template:
    metadata:
      labels:
        app: gateway-api
        app_gateway_auth_policy: enabled
        gateway-api-pdb: enabled
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: for
                    operator: In
                    values:
                      - backend
      serviceAccountName: gatewayapi-sa
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://*:8080/
          image: gatewayapi:istio
          name: gateway-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-api
  name: gatewayapi-svc
  namespace: backend
spec:
  type: ClusterIP
  ports:
    - name: "gateway-api-http"
      port: 8080 # Port exposed by the service within the cluster
      targetPort: 8080 # Port on which the gateway API container listens
  selector:
    app: gateway-api
