apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service2
    app_pod_auth_policy: enabled
  name: service2
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service2
        app_pod_auth_policy: enabled
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://*:8080/
          image: service2:istio
          name: service2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service2
  name: ms2
  namespace: backend
spec:
  type: ClusterIP
  ports:
    - name: "service2-http"
      port: 8080 # Port exposed by the service within the cluster
      targetPort: 8080 # Port on which the service2 container listens
  selector:
    app: service2
